-- ==========================================================
-- Update menu_items.image_url from Menu img files
-- Match key: name_en  (English menu name = file name without extension)
-- Run in pgAdmin Query Tool. Wrapped in a transaction so you can ROLLBACK.
-- ==========================================================
BEGIN;

-- ---- Foods (99 images) ----
UPDATE menu_items SET image_url = '/uploads/Foods/Basil Fried (Pad Kra Pao).jpg' WHERE name_en = 'Basil Fried (Pad Kra Pao)';
UPDATE menu_items SET image_url = '/uploads/Foods/Basil Fried Rice with Century Egg.jpg' WHERE name_en = 'Basil Fried Rice with Century Egg';
UPDATE menu_items SET image_url = '/uploads/Foods/Basil Fried Rice with Glass Noodle and Minced Pork.jpg' WHERE name_en = 'Basil Fried Rice with Glass Noodle and Minced Pork';
UPDATE menu_items SET image_url = '/uploads/Foods/Basil Fried Rice with Glass Noodles.jpg' WHERE name_en = 'Basil Fried Rice with Glass Noodles';
UPDATE menu_items SET image_url = '/uploads/Foods/Cha-Kang-Rao Grass Jelly.jpg' WHERE name_en = 'Cha-Kang-Rao Grass Jelly';
UPDATE menu_items SET image_url = '/uploads/Foods/Chicken Breast Coconut Curry.jpg' WHERE name_en = 'Chicken Breast Coconut Curry';
UPDATE menu_items SET image_url = '/uploads/Foods/Chicken Nuggets.jpg' WHERE name_en = 'Chicken Nuggets';
UPDATE menu_items SET image_url = '/uploads/Foods/Chicken Pops.jpg' WHERE name_en = 'Chicken Pops';
UPDATE menu_items SET image_url = '/uploads/Foods/Chicken Sticks.jpg' WHERE name_en = 'Chicken Sticks';
UPDATE menu_items SET image_url = '/uploads/Foods/Chicken Tendons.jpg' WHERE name_en = 'Chicken Tendons';
UPDATE menu_items SET image_url = '/uploads/Foods/Crispy Catfish Salad with Spicy Mango Dressing.jpg' WHERE name_en = 'Crispy Catfish Salad with Spicy Mango Dressing';
UPDATE menu_items SET image_url = '/uploads/Foods/Crispy Chicken with Lime Cream Sauce.jpg' WHERE name_en = 'Crispy Chicken with Lime Cream Sauce';
UPDATE menu_items SET image_url = '/uploads/Foods/Crispy Fried Morning Glory Salad.jpg' WHERE name_en = 'Crispy Fried Morning Glory Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Crispy Shrimp with Lime Cream Sauce.jpg' WHERE name_en = 'Crispy Shrimp with Lime Cream Sauce';
UPDATE menu_items SET image_url = '/uploads/Foods/Crying Tiger (Grilled Beef RibeyeBrisket).jpg' WHERE name_en = 'Crying Tiger (Grilled Beef RibeyeBrisket)';
UPDATE menu_items SET image_url = '/uploads/Foods/Fried Frog with Garlic and Pepper.jpg' WHERE name_en = 'Fried Frog with Garlic and Pepper';
UPDATE menu_items SET image_url = '/uploads/Foods/Fried Rice.jpg' WHERE name_en = 'Fried Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Fries with Cheese Sauce.jpg' WHERE name_en = 'Fries with Cheese Sauce';
UPDATE menu_items SET image_url = '/uploads/Foods/Fries.jpg' WHERE name_en = 'Fries';
UPDATE menu_items SET image_url = '/uploads/Foods/Grass Jelly with Fresh Milk.jpg' WHERE name_en = 'Grass Jelly with Fresh Milk';
UPDATE menu_items SET image_url = '/uploads/Foods/Grilled Pork Neck.jpg' WHERE name_en = 'Grilled Pork Neck';
UPDATE menu_items SET image_url = '/uploads/Foods/Keropok (Deep-Fried Fish Crackers).jpg' WHERE name_en = 'Keropok (Deep-Fried Fish Crackers)';
UPDATE menu_items SET image_url = '/uploads/Foods/Koh-Kae BBQ Peanuts.jpg' WHERE name_en = 'Koh-Kae BBQ Peanuts';
UPDATE menu_items SET image_url = '/uploads/Foods/Koh-Kae Salted Broad Beans.jpg' WHERE name_en = 'Koh-Kae Salted Broad Beans';
UPDATE menu_items SET image_url = '/uploads/Foods/Koh-Kae Salted Cashews.jpg' WHERE name_en = 'Koh-Kae Salted Cashews';
UPDATE menu_items SET image_url = '/uploads/Foods/Koh-Kae Salted Peanuts.jpg' WHERE name_en = 'Koh-Kae Salted Peanuts';
UPDATE menu_items SET image_url = '/uploads/Foods/Koh-Kae Wasabi Peanuts.jpg' WHERE name_en = 'Koh-Kae Wasabi Peanuts';
UPDATE menu_items SET image_url = '/uploads/Foods/Larb (Spicy Thai Minced Meat Salad).jpg' WHERE name_en = 'Larb (Spicy Thai Minced Meat Salad)';
UPDATE menu_items SET image_url = '/uploads/Foods/Lay_s Nori Seaweed.jpg' WHERE name_en = 'Lay_s Nori Seaweed';
UPDATE menu_items SET image_url = '/uploads/Foods/Lay_s Rock Extra BBQ.jpg' WHERE name_en = 'Lay_s Rock Extra BBQ';
UPDATE menu_items SET image_url = '/uploads/Foods/Lay_s Rock Original.jpg' WHERE name_en = 'Lay_s Rock Original';
UPDATE menu_items SET image_url = '/uploads/Foods/Minced Pork Coconut Curry with Wild Betel Leaves.jpg' WHERE name_en = 'Minced Pork Coconut Curry with Wild Betel Leaves';
UPDATE menu_items SET image_url = '/uploads/Foods/Nam Tok (Thai Spicy Grilled Meat Salad).jpg' WHERE name_en = 'Nam Tok (Thai Spicy Grilled Meat Salad)';
UPDATE menu_items SET image_url = '/uploads/Foods/Pad See Ew (Stir-Fried Rice Noodles with Soy Sauce).jpg' WHERE name_en = 'Pad See Ew (Stir-Fried Rice Noodles with Soy Sauce)';
UPDATE menu_items SET image_url = '/uploads/Foods/Rad Na (Noodles in Gravy Sauce).jpg' WHERE name_en = 'Rad Na (Noodles in Gravy Sauce)';
UPDATE menu_items SET image_url = '/uploads/Foods/Raw Shrimps in Fish Sauce.jpg' WHERE name_en = 'Raw Shrimps in Fish Sauce';
UPDATE menu_items SET image_url = '/uploads/Foods/Ruen Kao Special Spicy Salad.jpg' WHERE name_en = 'Ruen Kao Special Spicy Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Scalded Cockles.jpg' WHERE name_en = 'Scalded Cockles';
UPDATE menu_items SET image_url = '/uploads/Foods/Scalded Fish Balls with Dip.jpg' WHERE name_en = 'Scalded Fish Balls with Dip';
UPDATE menu_items SET image_url = '/uploads/Foods/Scalded Seabass with Dip.webp' WHERE name_en = 'Scalded Seabass with Dip';
UPDATE menu_items SET image_url = '/uploads/Foods/Scalded Seafood with Dip.jpg' WHERE name_en = 'Scalded Seafood with Dip';
UPDATE menu_items SET image_url = '/uploads/Foods/Sour Curry (Kaeng Som).jpg' WHERE name_en = 'Sour Curry (Kaeng Som)';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Century Egg Salad.jpg' WHERE name_en = 'Spicy Century Egg Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Chinese Sausage Salad.jpg' WHERE name_en = 'Spicy Chinese Sausage Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Cockle Salad.jpg' WHERE name_en = 'Spicy Cockle Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Crispy Omelet Salad.jpg' WHERE name_en = 'Spicy Crispy Omelet Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Crispy Pork Salad.jpg' WHERE name_en = 'Spicy Crispy Pork Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Fermented Pork Sausage Salad.jpg' WHERE name_en = 'Spicy Fermented Pork Sausage Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Fried Egg Salad.webp' WHERE name_en = 'Spicy Fried Egg Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Glass Noodles Salad with Chicken Sausage.jpg' WHERE name_en = 'Spicy Glass Noodles Salad with Chicken Sausage';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Glass Noodles Salad with Vietnamese Pork Sausage.jpg' WHERE name_en = 'Spicy Glass Noodles Salad with Vietnamese Pork Sausage';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Kelp Noodles Salad.jpg' WHERE name_en = 'Spicy Kelp Noodles Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Lime Beef Salad.jpg' WHERE name_en = 'Spicy Lime Beef Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Lime Pork Salad.jpg' WHERE name_en = 'Spicy Lime Pork Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Mango Salad.jpg' WHERE name_en = 'Spicy Mango Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Mixed Seafood-Meat Salad.jpg' WHERE name_en = 'Spicy Mixed Seafood-Meat Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Raw Shrimp Salad.jpg' WHERE name_en = 'Spicy Raw Shrimp Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Rice Noodles Salad with Mackerel.jpg' WHERE name_en = 'Spicy Rice Noodles Salad with Mackerel';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Salted Egg Salad.jpg' WHERE name_en = 'Spicy Salted Egg Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Shrimp Salad with Lemongrass (Pla Goong).jpg' WHERE name_en = 'Spicy Shrimp Salad with Lemongrass (Pla Goong)';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Catfish.jpg' WHERE name_en = 'Spicy Stir-Fried Catfish';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Curry Paste on Rice.jpg' WHERE name_en = 'Spicy Stir-Fried Curry Paste on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Eel.jpg' WHERE name_en = 'Spicy Stir-Fried Eel';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Frog.jpg' WHERE name_en = 'Spicy Stir-Fried Frog';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Red Curry Paste on Rice.jpg' WHERE name_en = 'Spicy Stir-Fried Red Curry Paste on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Sea Catfish.jpg' WHERE name_en = 'Spicy Stir-Fried Sea Catfish';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Seafood on Rice.jpg' WHERE name_en = 'Spicy Stir-Fried Seafood on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Stir-Fried Wild Boar.jpg' WHERE name_en = 'Spicy Stir-Fried Wild Boar';
UPDATE menu_items SET image_url = '/uploads/Foods/Spicy Three Crispy Salad.jpg' WHERE name_en = 'Spicy Three Crispy Salad';
UPDATE menu_items SET image_url = '/uploads/Foods/Steamed Rice.jpg' WHERE name_en = 'Steamed Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Chili & Salt on Rice.jpg' WHERE name_en = 'Stir-Fried Chili & Salt on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Chinese Kale on Rice.jpg' WHERE name_en = 'Stir-Fried Chinese Kale on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Chinese Kale.jpg' WHERE name_en = 'Stir-Fried Chinese Kale';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Clams with Chili Paste.webp' WHERE name_en = 'Stir-Fried Clams with Chili Paste';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Curry Paste on Rice.webp' WHERE name_en = 'Stir-Fried Curry Paste on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Curry Paste.jpg' WHERE name_en = 'Stir-Fried Curry Paste';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Fresh Chili.jpg' WHERE name_en = 'Stir-Fried Fresh Chili';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Glass Noodles.jpg' WHERE name_en = 'Stir-Fried Glass Noodles';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Holy Basil on Rice (Pad Ka Pao).jpg' WHERE name_en = 'Stir-Fried Holy Basil on Rice (Pad Ka Pao)';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Liang Leaves with Egg.webp' WHERE name_en = 'Stir-Fried Liang Leaves with Egg';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Mixed Vegetables.jpg' WHERE name_en = 'Stir-Fried Mixed Vegetables';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Morning Glory.webp' WHERE name_en = 'Stir-Fried Morning Glory';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Red Curry Paste on Rice.jpg' WHERE name_en = 'Stir-Fried Red Curry Paste on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Shrimps with Stink Beans and Shrimp Paste.jpg' WHERE name_en = 'Stir-Fried Shrimps with Stink Beans and Shrimp Paste';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Spicy Herbs (Khee Mao).jpg' WHERE name_en = 'Stir-Fried Spicy Herbs (Khee Mao)';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried Stink Beans with Shrimps.jpg' WHERE name_en = 'Stir-Fried Stink Beans with Shrimps';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried with Chili Paste on Rice.jpg' WHERE name_en = 'Stir-Fried with Chili Paste on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried with Curry Powder on Rice.jpg' WHERE name_en = 'Stir-Fried with Curry Powder on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried with Fish Sauce on Rice.jpg' WHERE name_en = 'Stir-Fried with Fish Sauce on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried with Fresh Chili on Rice.jpg' WHERE name_en = 'Stir-Fried with Fresh Chili on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried with Garlic and Pepper on Rice.jpg' WHERE name_en = 'Stir-Fried with Garlic and Pepper on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Stir-Fried with Oyster Sauce on Rice.jpg' WHERE name_en = 'Stir-Fried with Oyster Sauce on Rice';
UPDATE menu_items SET image_url = '/uploads/Foods/Sunflower Seeds.jpg' WHERE name_en = 'Sunflower Seeds';
UPDATE menu_items SET image_url = '/uploads/Foods/Tasto Crab Stick.jpg' WHERE name_en = 'Tasto Crab Stick';
UPDATE menu_items SET image_url = '/uploads/Foods/Tasto Seaweed.jpg' WHERE name_en = 'Tasto Seaweed';
UPDATE menu_items SET image_url = '/uploads/Foods/Tasto.jpg' WHERE name_en = 'Tasto';
UPDATE menu_items SET image_url = '/uploads/Foods/Tofu Clear Soup.jpg' WHERE name_en = 'Tofu Clear Soup';
UPDATE menu_items SET image_url = '/uploads/Foods/Tom Kha Gai (Chicken Coconut Soup).jpg' WHERE name_en = 'Tom Kha Gai (Chicken Coconut Soup)';
UPDATE menu_items SET image_url = '/uploads/Foods/Tom Yum.jpg' WHERE name_en = 'Tom Yum';

-- ---- Drinks (93 images) ----
UPDATE menu_items SET image_url = '/uploads/Drinks/Arcobrau Helles.jpg' WHERE name_en = 'Arcobrau Helles';
UPDATE menu_items SET image_url = '/uploads/Drinks/Cabernet Sauvignon.jpg' WHERE name_en = 'Cabernet Sauvignon';
UPDATE menu_items SET image_url = '/uploads/Drinks/Cantaloupe Soda.png' WHERE name_en = 'Cantaloupe Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Cantaloupe Tea.png' WHERE name_en = 'Cantaloupe Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Chang (Large).jpg' WHERE name_en = 'Chang (Large)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Chang (Small).jpg' WHERE name_en = 'Chang (Small)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Coca-Cola (Coke).jpg' WHERE name_en = 'Coca-Cola (Coke)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Cocoa Green Tea.png' WHERE name_en = 'Cocoa Green Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Cocoa Tea Love.png' WHERE name_en = 'Cocoa Tea Love';
UPDATE menu_items SET image_url = '/uploads/Drinks/Coke Zero.jpg' WHERE name_en = 'Coke Zero';
UPDATE menu_items SET image_url = '/uploads/Drinks/Cold Towel 9x9.webp' WHERE name_en = 'Cold Towel 9x9';
UPDATE menu_items SET image_url = '/uploads/Drinks/Corona Extra (1).jpg' WHERE name_en = 'Corona Extra (1)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Corona Extra (2).jpg' WHERE name_en = 'Corona Extra (2)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Drinking Water.jpg' WHERE name_en = 'Drinking Water';
UPDATE menu_items SET image_url = '/uploads/Drinks/Erdinger Dunkle.jpg' WHERE name_en = 'Erdinger Dunkle';
UPDATE menu_items SET image_url = '/uploads/Drinks/Fanta Green.jpg' WHERE name_en = 'Fanta Green';
UPDATE menu_items SET image_url = '/uploads/Drinks/Fanta Orange.jpg' WHERE name_en = 'Fanta Orange';
UPDATE menu_items SET image_url = '/uploads/Drinks/Fanta Red.jpg' WHERE name_en = 'Fanta Red';
UPDATE menu_items SET image_url = '/uploads/Drinks/Grape Soda.png' WHERE name_en = 'Grape Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Grape Tea.png' WHERE name_en = 'Grape Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Green Apple Soda.png' WHERE name_en = 'Green Apple Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Green Apple Tea.png' WHERE name_en = 'Green Apple Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Green Milk (Iced Sweet Green Milk).png' WHERE name_en = 'Green Milk (Iced Sweet Green Milk)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Green Soda (Cream Soda).png' WHERE name_en = 'Green Soda (Cream Soda)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Heineken (Large).jpg' WHERE name_en = 'Heineken (Large)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Heineken (Small).jpg' WHERE name_en = 'Heineken (Small)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Hoegaarden Rosee.jpg' WHERE name_en = 'Hoegaarden Rosee';
UPDATE menu_items SET image_url = '/uploads/Drinks/Hoegaarden Witbier.jpg' WHERE name_en = 'Hoegaarden Witbier';
UPDATE menu_items SET image_url = '/uploads/Drinks/Honey Lemon Tea.png' WHERE name_en = 'Honey Lemon Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Honey Lime Soda.png' WHERE name_en = 'Honey Lime Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Honey Soda.png' WHERE name_en = 'Honey Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Honey Tea.png' WHERE name_en = 'Honey Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Hong Thong (Flat).jpg' WHERE name_en = 'Hong Thong (Flat)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Hong Thong (Round).jpg' WHERE name_en = 'Hong Thong (Round)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Americano.png' WHERE name_en = 'Iced Americano';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Black Tea.png' WHERE name_en = 'Iced Black Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Cappuccino.png' WHERE name_en = 'Iced Cappuccino';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Cocoa.png' WHERE name_en = 'Iced Cocoa';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Espresso.png' WHERE name_en = 'Iced Espresso';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Green Milk Tea.png' WHERE name_en = 'Iced Green Milk Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Honey Americano.png' WHERE name_en = 'Iced Honey Americano';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Honey Lime Americano.png' WHERE name_en = 'Iced Honey Lime Americano';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Latte.png' WHERE name_en = 'Iced Latte';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Mocha.png' WHERE name_en = 'Iced Mocha';
UPDATE menu_items SET image_url = '/uploads/Drinks/Iced Ovaltine.png' WHERE name_en = 'Iced Ovaltine';
UPDATE menu_items SET image_url = '/uploads/Drinks/Kwai Beer.jpg' WHERE name_en = 'Kwai Beer';
UPDATE menu_items SET image_url = '/uploads/Drinks/Lemon Tea.png' WHERE name_en = 'Lemon Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Leo (Large).jpg' WHERE name_en = 'Leo (Large)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Leo (Small).jpg' WHERE name_en = 'Leo (Small)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Lime Soda.png' WHERE name_en = 'Lime Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Long Green Tea.png' WHERE name_en = 'Long Green Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Lychee Soda.png' WHERE name_en = 'Lychee Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Lychee Tea.png' WHERE name_en = 'Lychee Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Magners.jpg' WHERE name_en = 'Magners';
UPDATE menu_items SET image_url = '/uploads/Drinks/Mango Soda.png' WHERE name_en = 'Mango Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Mango Tea.png' WHERE name_en = 'Mango Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Meridian (Flat).jpg' WHERE name_en = 'Meridian (Flat)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Meridian (Round).jpg' WHERE name_en = 'Meridian (Round)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Moose Cider Original.jpg' WHERE name_en = 'Moose Cider Original';
UPDATE menu_items SET image_url = '/uploads/Drinks/Moose Indy Summer.jpg' WHERE name_en = 'Moose Indy Summer';
UPDATE menu_items SET image_url = '/uploads/Drinks/Muay Thai Chokdee.jpg' WHERE name_en = 'Muay Thai Chokdee';
UPDATE menu_items SET image_url = '/uploads/Drinks/Mud Milk Tea.png' WHERE name_en = 'Mud Milk Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Orange Soda.png' WHERE name_en = 'Orange Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Orange Tea.png' WHERE name_en = 'Orange Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Pink Milk (Iced Sweet Pink Milk).png' WHERE name_en = 'Pink Milk (Iced Sweet Pink Milk)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Plum Lemon Soda.webp' WHERE name_en = 'Plum Lemon Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Plum Soda.png' WHERE name_en = 'Plum Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Plum Tea.png' WHERE name_en = 'Plum Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Raven IPA.webp' WHERE name_en = 'Raven IPA';
UPDATE menu_items SET image_url = '/uploads/Drinks/Raven.jpg' WHERE name_en = 'Raven';
UPDATE menu_items SET image_url = '/uploads/Drinks/Red Soda (Salak Flavored Soda).png' WHERE name_en = 'Red Soda (Salak Flavored Soda)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Regency (Flat).jpg' WHERE name_en = 'Regency (Flat)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Regency (Round).jpg' WHERE name_en = 'Regency (Round)';
UPDATE menu_items SET image_url = '/uploads/Drinks/SPY Blue Lime.jpg' WHERE name_en = 'SPY Blue Lime';
UPDATE menu_items SET image_url = '/uploads/Drinks/SPY Classic.jpg' WHERE name_en = 'SPY Classic';
UPDATE menu_items SET image_url = '/uploads/Drinks/SPY Mixed Berry.jpg' WHERE name_en = 'SPY Mixed Berry';
UPDATE menu_items SET image_url = '/uploads/Drinks/SPY Red.jpg' WHERE name_en = 'SPY Red';
UPDATE menu_items SET image_url = '/uploads/Drinks/SPY Zab Kiss.jpg' WHERE name_en = 'SPY Zab Kiss';
UPDATE menu_items SET image_url = '/uploads/Drinks/SangSom (Flat).webp' WHERE name_en = 'SangSom (Flat)';
UPDATE menu_items SET image_url = '/uploads/Drinks/SangSom (Round).jpg' WHERE name_en = 'SangSom (Round)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Singha (Large).jpg' WHERE name_en = 'Singha (Large)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Singha (Small).jpg' WHERE name_en = 'Singha (Small)';
UPDATE menu_items SET image_url = '/uploads/Drinks/Soda Water.jpg' WHERE name_en = 'Soda Water';
UPDATE menu_items SET image_url = '/uploads/Drinks/Sprite.jpg' WHERE name_en = 'Sprite';
UPDATE menu_items SET image_url = '/uploads/Drinks/Strawberry Soda.png' WHERE name_en = 'Strawberry Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Strawberry Tea.png' WHERE name_en = 'Strawberry Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Thai Iced Milk Tea.jpg' WHERE name_en = 'Thai Iced Milk Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Watermelon Soda.png' WHERE name_en = 'Watermelon Soda';
UPDATE menu_items SET image_url = '/uploads/Drinks/Watermelon Tea.png' WHERE name_en = 'Watermelon Tea';
UPDATE menu_items SET image_url = '/uploads/Drinks/Wila.jpg' WHERE name_en = 'Wila';
UPDATE menu_items SET image_url = '/uploads/Drinks/crispy.jpg' WHERE name_en = 'crispy';
UPDATE menu_items SET image_url = '/uploads/Drinks/red horse.jpg' WHERE name_en = 'red horse';
UPDATE menu_items SET image_url = '/uploads/Drinks/tapper.jpg' WHERE name_en = 'tapper';

-- ==========================================================
-- CHECK: menu rows that still have NO image after the updates
-- (name_en likely differs from the file name — fix by hand)
-- ==========================================================
-- SELECT id, category, name, name_en, image_url FROM menu_items
--   WHERE image_url IS NULL OR image_url NOT LIKE '/uploads/%' ORDER BY category, name_en;

-- Happy? then run:  COMMIT;   Wrong?  run:  ROLLBACK;
COMMIT;
